version: "2"
services:
  app:
    container_name: app-stage
    restart: always
    build: .
    ports:
      - '8080:8080'
    links:
      - mongo
  mongo:
    container_name: mongo-stage
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
    
